# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

class_probabilities <- function(X, beta) {
    .Call(`_GroupHW_class_probabilities`, X, beta)
}

objective_fx <- function(X, Y, beta, lambda, prods) {
    .Call(`_GroupHW_objective_fx`, X, Y, beta, lambda, prods)
}

compute_W_k <- function(P_k) {
    .Call(`_GroupHW_compute_W_k`, P_k)
}

update_fx <- function(X, Y, beta, lambda, eta, probabilities) {
    .Call(`_GroupHW_update_fx`, X, Y, beta, lambda, eta, probabilities)
}

LRMultiClass_c <- function(X, y, beta_init, numIter = 50L, eta = 0.1, lambda = 1) {
    .Call(`_GroupHW_LRMultiClass_c`, X, y, beta_init, numIter, eta, lambda)
}

square_mat <- function(X, K) {
    .Call(`_GroupHW_square_mat`, X, K)
}

euc_function_c <- function(X, X_squared, mu) {
    .Call(`_GroupHW_euc_function_c`, X, X_squared, mu)
}

MyKmeans_c <- function(X, K, M, numIter = 100L) {
    .Call(`_GroupHW_MyKmeans_c`, X, K, M, numIter)
}

